//! Terminal section: grid density, scrollback, selection, and suggestions.

use super::{list, opt, slider, text, toggle, Control, ListKind, Section, Setting, Slider};

pub(super) fn settings() -> Vec<Setting> {
    let s = Section::Terminal;
    vec![
        slider(
            "font-size",
            "Font size",
            "Terminal font size in points.",
            s,
            |o| o.font_size,
            (6.0, 72.0, 1.0),
            false,
        ),
        slider(
            "adjust-cell-width",
            "Cell width adjust",
            "Pixels added to (or removed from) every cell's width.",
            s,
            |o| o.adjust_cell_width as f32,
            (-64.0, 64.0, 1.0),
            true,
        ),
        slider(
            "adjust-cell-height",
            "Cell height adjust",
            "Pixels added to (or removed from) every cell's height.",
            s,
            |o| o.adjust_cell_height as f32,
            (-64.0, 64.0, 1.0),
            true,
        ),
        slider(
            "window-padding-x",
            "Padding X",
            "Horizontal inner margin, in pixels.",
            s,
            |o| o.window_padding_x as f32,
            (0.0, 200.0, 1.0),
            true,
        ),
        slider(
            "window-padding-y",
            "Padding Y",
            "Vertical inner margin, in pixels.",
            s,
            |o| o.window_padding_y as f32,
            (0.0, 200.0, 1.0),
            true,
        ),
        auto_slider(
            "window-width",
            "Window width (cells)",
            "New-window width in cells; 0 means auto.",
            s,
            |o| o.window_width as f32,
            (0.0, 500.0, 1.0),
        ),
        auto_slider(
            "window-height",
            "Window height (cells)",
            "New-window height in cells; 0 means auto.",
            s,
            |o| o.window_height as f32,
            (0.0, 500.0, 1.0),
        ),
        slider(
            "scrollback-limit",
            "Scrollback lines",
            "Lines of history kept per pane.",
            s,
            |o| o.scrollback_limit as f32,
            (0.0, 1_000_000.0, 1000.0),
            true,
        ),
        slider(
            "mouse-scroll-multiplier",
            "Scroll multiplier",
            "Speed factor applied to mouse-wheel scrolling.",
            s,
            |o| o.mouse_scroll_multiplier,
            (0.01, 10_000.0, 0.5),
            false,
        ),
        toggle(
            "mouse-hide-while-typing",
            "Hide mouse while typing",
            "Hide the pointer until the mouse moves again.",
            s,
            |o| o.mouse_hide_while_typing,
        ),
        toggle(
            "smart-select",
            "Smart selection",
            "Double-click selects whole URLs, paths, emails, and hashes.",
            s,
            |o| o.smart_select,
        ),
        text(
            "word-chars",
            "Word characters",
            "Extra characters treated as part of a word when selecting.",
            s,
            |o| o.word_chars.clone(),
            "/-_.~",
        ),
        toggle(
            "middle-click-paste",
            "Middle-click paste",
            "Paste the current selection on a middle click.",
            s,
            |o| o.middle_click_paste,
        ),
        toggle(
            "focus-follows-mouse",
            "Focus follows mouse",
            "Focus the split under the pointer without clicking.",
            s,
            |o| o.focus_follows_mouse,
        ),
        toggle(
            "timestamps",
            "Line timestamps",
            "Show a per-line timestamp gutter.",
            s,
            |o| o.timestamps,
        ),
        toggle(
            "visual-bell",
            "Visual bell",
            "Flash the pane briefly when the bell rings.",
            s,
            |o| o.visual_bell,
        ),
        toggle(
            "autosuggest-ghost",
            "Inline suggestions (ghost text)",
            "Fish-style completion of the current command, inline.",
            s,
            |o| o.autosuggest_ghost,
        ),
        toggle(
            "autosuggest-popup",
            "Completion popup",
            "A dropdown of ranked completions under the cursor.",
            s,
            |o| o.autosuggest_popup,
        ),
        toggle(
            "autosuggest-tab",
            "Tab cycles completions",
            "Tab cycles inline completions instead of reaching the shell.",
            s,
            |o| o.autosuggest_tab,
        ),
        toggle(
            "autosuggest-ai",
            "AI suggestions",
            "Ask Claude for a next command when nothing local matches.",
            s,
            |o| o.autosuggest_ai,
        ),
        toggle(
            "autosuggest-history",
            "Suggest from history",
            "Use captured command history as a suggestion source.",
            s,
            |o| o.autosuggest_history,
        ),
        toggle(
            "autosuggest-commands",
            "Suggest common commands",
            "Use the built-in common-command list as a source.",
            s,
            |o| o.autosuggest_commands,
        ),
        toggle(
            "autosuggest-paths",
            "Complete file paths",
            "Complete filesystem paths from the working directory.",
            s,
            |o| o.autosuggest_paths,
        ),
        toggle(
            "autosuggest-assist",
            "Rank with assist model",
            "Rank suggestions with the local model instead of recency.",
            s,
            |o| o.autosuggest_assist,
        ),
        slider(
            "unfocused-split-opacity",
            "Unfocused split opacity",
            "How much unfocused splits dim.",
            s,
            |o| o.unfocused_split_opacity,
            (0.15, 1.0, 0.05),
            false,
        ),
        slider(
            "background-opacity",
            "Background opacity",
            "Window background alpha; below 1 the desktop shows through.",
            s,
            |o| o.background_opacity,
            (0.2, 1.0, 0.05),
            false,
        ),
        text(
            "background-image",
            "Background image",
            "Image drawn behind the terminal (best with opacity below 1).",
            s,
            |o| opt(&o.background_image),
            "/path/to/image.png",
        ),
        text(
            "badge",
            "Badge watermark",
            "Faint text drawn in each pane; {cwd} and {host} expand.",
            s,
            |o| opt(&o.badge),
            "{host}  \u{b7}  {cwd}",
        ),
        text(
            "split-divider-color",
            "Split divider color",
            "Divider line color as #rrggbb.",
            s,
            |o| opt(&o.split_divider_color),
            "Theme",
        ),
        list(
            ListKind::Redact,
            "Regexes masked with \u{2022} when copying, so secrets stay put.",
            s,
        ),
        list(
            ListKind::Trigger,
            "Notify when output matches a regex: regex | title.",
            s,
        ),
        list(
            ListKind::Snippet,
            "Commands inserted from the snippet picker: label | command.",
            s,
        ),
        list(
            ListKind::Profile,
            "Tabs launched from the profile picker: label | command.",
            s,
        ),
    ]
}

/// A slider whose zero displays as "auto".
fn auto_slider(
    key: &'static str,
    label: &'static str,
    desc: &'static str,
    section: Section,
    get: fn(&config::Options) -> f32,
    range: (f32, f32, f32),
) -> Setting {
    let (min, max, step) = range;
    Setting {
        key,
        label,
        desc,
        section,
        control: Control::Slider(Slider {
            get,
            min,
            max,
            step,
            int: true,
            auto_zero: true,
        }),
    }
}
