// Prompt Designer — an IPC panel plugin for Sinclair.
//
// Lets you design a shell prompt by toggling segments / picking a symbol and
// color, then writes the generated PS1 (bash) or PROMPT (zsh) to
// ~/.config/prompt-designer/prompt.sh and sources it from your rc file via a
// single managed block. State persists in design.json so each invocation
// (Sinclair spawns the plugin fresh per event) reads the current design.

import { homedir } from "node:os";
import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Block =
  | { type: "section"; title: string }
  | { type: "text"; text: string; dimmed?: boolean }
  | { type: "divider" }
  | { type: "kv"; key: string; value: string }
  | { type: "badge"; label: string; color?: string }
  | { type: "button"; id: string; label: string; variant?: string }
  | { type: "row"; children: Block[] };

interface Response {
  title?: string;
  blocks: Block[];
  run?: { text: string; target?: string }[];
}

interface Design {
  userhost: boolean;
  cwd: boolean;
  git: boolean;
  time: boolean;
  symbol: string;
  color: string;
}

const DEFAULT: Design = {
  userhost: false,
  cwd: true,
  git: true,
  time: false,
  symbol: "❯",
  color: "cyan",
};

const SYMBOLS = ["❯", "➜", "$", "λ", "»"];
const COLORS = ["cyan", "green", "blue", "magenta", "yellow", "red", "white"];

const dir = join(homedir(), ".config", "prompt-designer");
const designPath = join(dir, "design.json");
const promptPath = join(dir, "prompt.sh");
const BEGIN = "# >>> prompt-designer >>>";
const END = "# <<< prompt-designer <<<";

// Escape regex metacharacters so the markers can change without breaking match.
const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const APPLY_RE = new RegExp(`${esc(BEGIN)}[\\s\\S]*?${esc(END)}`, "g");
const REMOVE_RE = new RegExp(`\\n*${esc(BEGIN)}[\\s\\S]*?${esc(END)}\\n*`, "g");

// Write via a temp file + rename so an interrupted write can't truncate or
// corrupt the target (important for the user's shell rc).
function writeAtomic(path: string, data: string) {
  const tmp = `${path}.pd-${process.pid}.tmp`;
  writeFileSync(tmp, data);
  renameSync(tmp, path);
}

function load(): Design {
  try {
    return { ...DEFAULT, ...JSON.parse(readFileSync(designPath, "utf8")) };
  } catch {
    return { ...DEFAULT };
  }
}

function save(d: Design) {
  mkdirSync(dir, { recursive: true });
  writeFileSync(designPath, JSON.stringify(d, null, 2));
}

function shellName(): "zsh" | "bash" {
  const sh = (process.env.SHELL || "").split("/").pop() || "";
  return sh.includes("bash") ? "bash" : "zsh";
}

function rcPath(shell: "zsh" | "bash"): string {
  return join(homedir(), shell === "bash" ? ".bashrc" : ".zshrc");
}

// A plain-text approximation of the prompt for the panel preview.
function preview(d: Design): string {
  const parts: string[] = [];
  if (d.userhost) parts.push("you@host");
  if (d.cwd) parts.push("~/dev/app");
  if (d.git) parts.push("(main)");
  if (d.time) parts.push("14:32");
  parts.push(d.symbol);
  return parts.join(" ");
}

// bash ANSI color code for a name.
function ansi(color: string): string {
  const map: Record<string, string> = {
    black: "30", red: "31", green: "32", yellow: "33",
    blue: "34", magenta: "35", cyan: "36", white: "37",
  };
  return map[color] ?? "36";
}

function snippet(d: Design, shell: "zsh" | "bash"): string {
  const sym = d.symbol;
  if (shell === "zsh") {
    const c = d.color;
    let p = "";
    if (d.userhost) p += `%F{${c}}%n@%m%f `;
    if (d.cwd) p += `%F{${c}}%~%f `;
    if (d.git) p += `%F{yellow}$(_pd_git)%f`;
    if (d.time) p += `%F{${c}}%*%f `;
    p += `%F{${c}}${sym}%f `;
    return [
      "# Generated by Prompt Designer — edit in the app, not here.",
      "setopt prompt_subst 2>/dev/null",
      "_pd_git() { local b; b=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) || return; print -n \"($b) \"; }",
      `PROMPT='${p}'`,
      "",
    ].join("\n");
  }
  // bash
  const col = `\\[\\e[${ansi(d.color)}m\\]`;
  const ylw = `\\[\\e[33m\\]`;
  const off = `\\[\\e[0m\\]`;
  let p = "";
  if (d.userhost) p += `${col}\\u@\\h${off} `;
  if (d.cwd) p += `${col}\\w${off} `;
  if (d.git) p += `${ylw}$(_pd_git)${off}`;
  if (d.time) p += `${col}\\t${off} `;
  p += `${col}${sym}${off} `;
  return [
    "# Generated by Prompt Designer — edit in the app, not here.",
    "_pd_git() { local b; b=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) || return; printf '(%s) ' \"$b\"; }",
    `PS1='${p}'`,
    "",
  ].join("\n");
}

function applyToShell(d: Design): string {
  const shell = shellName();
  mkdirSync(dir, { recursive: true });
  writeAtomic(promptPath, snippet(d, shell));

  const rc = rcPath(shell);
  let body = "";
  try {
    body = readFileSync(rc, "utf8");
  } catch {
    body = "";
  }
  const block = `${BEGIN}\n[ -f "${promptPath}" ] && source "${promptPath}"\n${END}`;
  if (body.includes(BEGIN)) {
    body = body.replace(APPLY_RE, block);
  } else {
    body = body.replace(/\s*$/, "") + `\n\n${block}\n`;
  }
  writeAtomic(rc, body);
  return rc;
}

function removeFromShell(): string {
  const rc = rcPath(shellName());
  try {
    const body = readFileSync(rc, "utf8");
    writeAtomic(rc, body.replace(REMOVE_RE, "\n"));
  } catch {
    /* nothing to remove */
  }
  return rc;
}

function render(d: Design): Response {
  const shell = shellName();
  const onoff = (b: boolean) => (b ? "on" : "off");
  const blocks: Block[] = [
    { type: "section", title: "Preview" },
    { type: "text", text: preview(d) },
    { type: "divider" },

    { type: "section", title: "Presets" },
    { type: "button", id: "preset:minimal", label: "Minimal", variant: "subtle" },
    { type: "button", id: "preset:classic", label: "Classic", variant: "subtle" },
    { type: "button", id: "preset:arrow", label: "Arrow", variant: "subtle" },

    { type: "section", title: "Segments" },
    { type: "button", id: "toggle:userhost", label: `user@host: ${onoff(d.userhost)}` },
    { type: "button", id: "toggle:cwd", label: `directory: ${onoff(d.cwd)}` },
    { type: "button", id: "toggle:git", label: `git branch: ${onoff(d.git)}` },
    { type: "button", id: "toggle:time", label: `time: ${onoff(d.time)}` },

    { type: "section", title: "Symbol" },
    {
      type: "row",
      children: SYMBOLS.map((s) => ({
        type: "button" as const,
        id: `symbol:${s}`,
        label: s,
        variant: s === d.symbol ? "filled" : "subtle",
      })),
    },

    { type: "section", title: "Color" },
  ];
  for (const c of COLORS) {
    blocks.push({
      type: "button",
      id: `color:${c}`,
      label: c,
      variant: c === d.color ? "filled" : "subtle",
    });
  }

  blocks.push({ type: "divider" });
  blocks.push({ type: "section", title: "Shell" });
  blocks.push({ type: "kv", key: "shell", value: shell });
  blocks.push({ type: "kv", key: "config", value: rcPath(shell).replace(homedir(), "~") });
  blocks.push({ type: "button", id: "apply", label: `Apply to ${shell}`, variant: "filled" });
  blocks.push({ type: "button", id: "remove", label: "Remove from shell", variant: "subtle" });

  return { title: "Prompt Designer", blocks };
}

function action(name: string, d: Design): Response {
  if (name.startsWith("toggle:")) {
    const key = name.slice(7) as keyof Design;
    if (typeof d[key] === "boolean") (d[key] as boolean) = !(d[key] as boolean);
    save(d);
    return render(d);
  }
  if (name.startsWith("symbol:")) {
    const s = name.slice(7);
    if (SYMBOLS.includes(s)) d.symbol = s; // allowlist: never interpolate arbitrary text into the shell snippet
    save(d);
    return render(d);
  }
  if (name.startsWith("color:")) {
    const c = name.slice(6);
    if (COLORS.includes(c)) d.color = c;
    save(d);
    return render(d);
  }
  if (name.startsWith("preset:")) {
    const p = name.slice(7);
    if (p === "minimal") Object.assign(d, { userhost: false, cwd: true, git: false, time: false, symbol: "❯" });
    if (p === "classic") Object.assign(d, { userhost: true, cwd: true, git: true, time: false, symbol: "$" });
    if (p === "arrow") Object.assign(d, { userhost: false, cwd: true, git: true, time: false, symbol: "➜" });
    save(d);
    return render(d);
  }
  if (name === "apply") {
    applyToShell(d);
    const r = render(d);
    r.run = [{ text: `source ${promptPath.replace(homedir(), "$HOME")}`, target: "pane" }];
    return r;
  }
  if (name === "remove") {
    removeFromShell();
    return render(d);
  }
  return render(d);
}

const req = JSON.parse((await Bun.stdin.text()) || "{}");
const design = load();
const resp: Response = req.kind === "action" ? action(req.action, design) : render(design);
console.log(JSON.stringify(resp));
